#!/bin/bash

set -e

if [[ $1 == "bash" ]]; then
  /bin/bash
  exit
fi

TEST_PARALLEL=4
#TEST_CMD="prove -lrs -j${TEST_PARALLEL}"
TEST_CMD="yath test -PDBIx::Class::Sims -PDBIx::Class -PMoose -j${TEST_PARALLEL}"

echo "Starting tests"
if [[ $1 == "cover" ]]; then
  shift
  carton exec -- cover -delete
  # Ignore the Carton-created library and ignore our test files.
  HARNESS_PERL_SWITCHES=-MDevel::Cover=+inc,local/lib/perl5,+ignore,'^t/' carton exec -- ${TEST_CMD} "$@"
  carton exec -- cover -coverage default,-pod
else
  carton exec -- ${TEST_CMD} "$@"
fi
