schema_class: 'MyApp::Schema'
connect_info:
  -
    'dbi:SQLite:dbname=:memory:'
  -
    ''
  -
    ''
connect_opts: 
  name_sep: '.'
  quote_char: '`'
  on_connect_call: 'use_foreign_keys'
deploy_opts: 
  quote_identifiers: 1
